CREATE TABLE BANK (
  ID INTEGER NOT NULL,
  BANK_NUMBER INTEGER NOT NULL,
  DESCRPTION VARCHAR(1000),
  SERVER_ADRESS VARCHAR(32) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SEQUENCE (
  SEQ_NAME VARCHAR(50) NOT NULL, 
  SEQ_COUNT INTEGER,
  PRIMARY KEY (SEQ_NAME)
);

INSERT INTO SEQUENCE (SEQ_NAME, SEQ_COUNT) VALUES ('SEQ_GEN', 1);

